
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.32014.148
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "dockerfile-WebAppTest", "dockerfile-WebAppTest.csproj", "{F255A152-3142-4902-B19A-287EB41F5F7C}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{F255A152-3142-4902-B19A-287EB41F5F7C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{F255A152-3142-4902-B19A-287EB41F5F7C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{F255A152-3142-4902-B19A-287EB41F5F7C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{F255A152-3142-4902-B19A-287EB41F5F7C}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {387208CA-8736-4C61-BF23-12EE2B2AA2F3}
	EndGlobalSection
EndGlobal
